version: 0.0
os: linux
files:
  - source: /
    destination: /opt/test
hooks:
  ApplicationStop:
    - location: scripts/appStop.sh
  AfterInstall:
    - location: scripts/afterInstall.sh
  ApplicationStart:
    - location: scripts/appStart.sh
   ValidateService:
    - location: scripts/appStatus.sh